[output.html.fold]
enable = true
level = 0

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]