name: www2.manual.grid.tf
on:
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.manual.grid.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.manual.grid.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www2/info_grid/
          git checkout development
          git log -1
          git fetch
          git reset --hard origin/development
          mdbook build -d docs

  job_two:
    needs: job_one
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Sleep and Run
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  job_three:
    needs: [job_one, job_two]
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www2.manual.grid.tf -w 404'